FROM ubuntu:latest
RUN apt-get update && apt-get install -y supervisor && apt-get install -y openjdk-8-jdk
RUN mkdir -p /var/log/supervisor
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY customer-service/target/customer-service-*.jar /app/
COPY lucky-winner/target/lucky-winner-*.jar /app/

EXPOSE 8081
EXPOSE 8082
EXPOSE 9001

ENTRYPOINT ["/usr/bin/supervisord"]
